name: Daily Weather Notifier

on:
  schedule:
    - cron: '18 19 * * *'   
  workflow_dispatch:         # lets you trigger it manually with a button

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather script
        run: python WeatherbotOM.py
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          LOCATION: ${{ secrets.LOCATION }}

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
